# Generated by Django 3.2.9 on 2021-11-20 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=100, null=True, unique=True)),
                ('password', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('conf_password', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('ip_address', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='zipFileData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('file_path', models.FileField(blank=True, default='', max_length=255, null=True, upload_to='userData/zip_files')),
                ('media_ids', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ydltool_app.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='mp4VideosData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('file_path', models.FileField(blank=True, default='', max_length=255, null=True, upload_to='userData/mp4_songs')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ydltool_app.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='mp3SongsData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('file_path', models.FileField(blank=True, default='', max_length=255, null=True, upload_to='userData/mp3_songs')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ydltool_app.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='audioSongsData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('file_path', models.FileField(blank=True, default='', max_length=255, null=True, upload_to='userData/audio_songs')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ydltool_app.userinfo')),
            ],
        ),
    ]
