# Generated by Django 3.2.9 on 2021-11-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ydltool_app', '0002_videoinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='webpageurl',
            field=models.URLField(blank=True, default='', max_length=255, null=True),
        ),
    ]
